# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3bfe81d2d4cfcb82b65050cc7ef8f89716ca6990f58003b9e5fb2b5431408f6cedcc0305db404042135c995d988a0e6fa90ed8e399412c3572a8621260a0149

test:
  secret_key_base: f48dc20fe128511588152825d119459c4b25f11b9233609d53c492dd2c7ea1e63f99b5c71eb93a0ea05120156b72edaf1fa0583426d6278706f4c9a5af0cb8ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
